/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/start/': RouteRecordInfo<
      '/start/',
      '/start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/yueli/科学谱转换ABC规则V2.1': RouteRecordInfo<
      '/yueli/科学谱转换ABC规则V2.1',
      '/yueli/%E7%A7%91%E5%AD%A6%E8%B0%B1%E8%BD%AC%E6%8D%A2ABC%E8%A7%84%E5%88%99V2/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/yueli/简谱转换ABC规则V2.1': RouteRecordInfo<
      '/yueli/简谱转换ABC规则V2.1',
      '/yueli/%E7%AE%80%E8%B0%B1%E8%BD%AC%E6%8D%A2ABC%E8%A7%84%E5%88%99V2/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-press@0.28.1_@_cbdf0d3f20a1f1fbb096f6fbf5137b5a/node_modules/valaxy-theme-press/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.1_@babel+parser_d58b4902906eb2d2c1c0ff0aba1a2593/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/start/index.md': {
      routes:
        | '/start/'
      views:
        | never
    }
    'pages/yueli/科学谱转换ABC规则V2.1.md': {
      routes:
        | '/yueli/科学谱转换ABC规则V2.1'
      views:
        | never
    }
    'pages/yueli/简谱转换ABC规则V2.1.md': {
      routes:
        | '/yueli/简谱转换ABC规则V2.1'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
